apiVersion: v1
kind: Service
metadata:
  name: accountsdb
  labels:
    app: accountsdb
    tier: db
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  selector:
    app: accountsdb
    tier: db