x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://loki.safemoon.joshcorp.co/api/prom/push'

version: "3.7"
services: 
    traefik:
      image: "traefik:v2.4"
      container_name: "traefik"
      command:
          #- "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
      ports:
          - "80:80"
          - "8080:8080"
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
      networks:
          - bom
      logging: *default-logging

    # gf_agent:
    #   image: grafana/agent:v0.19.0
    #   container_name: gf_agent
    #   volumes:
    #     - /var/log:/var/log
    #     - /var/lib/docker:/var/lib/docker
    #     - ./config/agent.yaml:/etc/config.yaml
    #   command: --config.file=/etc/config.yaml

    adminer:
      image: adminer
      networks:
        - bom
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
        - "traefik.http.routers.adminer.entrypoints=web"
      logging: *default-logging


    ledgerdb:
      build: 
        context: ./src/ledger-db
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging

    balancereader:
      build:
        context: ./src/balancereader
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging
    
    ledgerwriter:
      build:
        context: ./src/ledgerwriter
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging

    transactionhistory:
      build:
        context: ./src/transactionhistory
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging

    accountsdb:
      build:
        context: ./src/accounts-db
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging

    userservice:
      build:
        context: ./src/userservice
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging

    contacts:
      build:
        context: ./src/contacts
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      logging: *default-logging
    
    frontend:
      build:
        context: ./src/frontend
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - ./root/.ssh:/root/.ssh
      networks:
        - bom
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.bom.loadbalancer.server.port=8080"
        - "traefik.http.routers.bom.rule=Host(`bom.localhost`)"
        - "traefik.http.routers.bom.entrypoints=web"
      logging: *default-logging

networks:
  bom:
    driver: bridge