apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./config
  - ./accountsdb
  # - ./balancereader
  # - ./contacts
  # - ./frontend
  # - ./ledgerdb
  # - ./ledgerwriter
  # - ./transactionhistory
  # - ./userservice


resources:
  - namespace.yaml

namespace: bom