server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

tempo:
  configs:
  - name: default
    receivers:
      zipkin:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:55681"
            cors_allowed_origins:
            - "*"
            cors_allowed_headers:
            - "*"
          grpc:
    attributes:
      actions:
        - action: upsert
          key: env
          value: local
    remote_write:
      - endpoint: https://tempo-otlp.safemoon.joshcorp.co

loki:
  positions_directory: /tmp/positions
  configs:
    - clients:
      - url: https://loki.safemoon.joshcorp.co/api/prom/push
      name: default
      scrape_configs:
        - job_name: compose-system
          static_configs:
          - targets:
            - localhost
            labels:
              job: varlogs
              __path__: /var/log/*.log
        
        - job_name: containers

          static_configs:
          - targets:
            - localhost
            labels:
              job: containerlogs
              __path__: /var/lib/docker/containers/*/*log

          pipeline_stages:
          
          - json:
              expressions:
                stream: stream
                attrs: attrs
                tag: attrs.tag

          - regex:
              expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
              source: "tag"

          - labels:
              tag:
              stream:
              image_name:
              container_name:
              image_id:
              container_id: