name: Build Accounts DB

on:
  pull_request:
    branches: [master]
    # paths:
    #   - 'src/accounts-db/*'
  push:
    branches: [master]
    # paths:
    #   - 'src/accounts-db/*'

jobs:
  build:
      name: Upload to ECR
      runs-on: self-hosted

      env:
        REPO_NAME: vre/accountsdb
        KUBE_PREFIX: /tmp/bom-deploy
        KUBE_IMAGE_FILE: accountsdb/statefulset.yaml
        SRC_PREFIX: ./bank-of-midgard
        SRC_DIR: src/accounts-db

      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRC_PREFIX }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-duration-seconds: 3599

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

        # Create repository, do nothing if it exists
      - name: Create Repository
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ env.REPO_NAME }}

      - name: Build, tag, and push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ env.SRC_PREFIX}}/${{ env.SRC_DIR }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: checkout kube
        uses: actions/checkout@master
        with:
          repository: HackSafemoon/bom-deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.KUBE_PREFIX }}

      - name: update manifest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: ./scripts/update-image.sh $ECR_REGISTRY $ECR_REPOSITORY $IMAGE_TAG ${{ env.KUBE_PREFIX }}/${{ env.KUBE_IMAGE_FILE }}

      - name: update kube
        run: |
          cd ${{ env.KUBE_PREFIX }}
          git add .
          git commit -m "updating ${{ env.REPO_NAME }} image"
          git push
